version: '2.2'
services:
  elasticsearch:
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.11.2'
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "bets:1:1"
      KAFKA_ADVERTISED_HOST_NAME: localhost # docker-machine ip
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"